In [1]:
pip install transformers pandas torch scikit-learn

In [3]:
pip install spacy

  Using cached smart_open-6.3.0-py3-none-any.whl (56 kB)
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
  Attempting uninstall: typing-extensions
    Found existing installation: typing-extensions 4.1.1
    Uninstalling typing-extensions-4.1.1:
      Successfully uninstalled typing-extensions-4.1.1
  Attempting uninstall: colorama
    Found existing installation: colorama 0.4.4
    Uninstalling colorama-0.4.4:
      Successfully uninstalled colorama-0.4.4
  Attempting uninstall: smart-open
    Found existing installation: smart-open 5.1.0
    Uninstalling smart-open-5.1.0:
      Successfully uninstalled smart-open-5.1.0
Note: you may need to restart the kernel to use updated packages.


In [4]:
pip install nltk

In [2]:
import pandas as pd
import numpy as np
import spacy
import nltk

In [3]:
data=pd.read_csv("Coursera.csv")

In [4]:
df=pd.DataFrame(data)
df

Course Name  \
0     Write A Feature Length Screenplay For Film Or ...   
1     Business Strategy: Business Model Canvas Analy...   
2                         Silicon Thin Film Solar Cells   
3                                  Finance for Managers   
4          Retrieve Data using Single-Table SQL Queries   
...                                                 ...   
3517  Capstone: Retrieving, Processing, and Visualiz...   
3518                   Patrick Henry: Forgotten Founder   
3519  Business intelligence and data analytics: Gene...   
3520                                Rigid Body Dynamics   
3521  Architecting with Google Kubernetes Engine: Pr...   

                                             University Difficulty Level  \
0                             Michigan State University         Beginner   
1                              Coursera Project Network         Beginner   
2                                   �cole Polytechnique         Advanced   
3                                  IESE Business School     Intermediate   
4                              Coursera Project Network         Beginner   
...                                                 ...              ...   
3517                             University of Michigan         Beginner   
3518                             University of Virginia     Intermediate   
3519                               Macquarie University         Advanced   
3520  Korea Advanced Institute of Science and Techno...         Beginner   
3521                                       Google Cloud     Intermediate   

     Course Rating                                         Course URL  \
0              4.8  https://www.coursera.org/learn/write-a-feature...   
1              4.8  https://www.coursera.org/learn/canvas-analysis...   
2              4.1  https://www.coursera.org/learn/silicon-thin-fi...   
3              4.8  https://www.coursera.org/learn/operational-fin...   
4              4.6  https://www.coursera.org/learn/single-table-sq...   
...            ...                                                ...   
3517           4.6  https://www.coursera.org/learn/python-data-vis...   
3518           4.9               https://www.coursera.org/learn/henry   
3519           4.6  https://www.coursera.org/learn/business-intell...   
3520           4.6  https://www.coursera.org/learn/rigid-body-dyna...   
3521           4.7  https://www.coursera.org/learn/deploying-secur...   

                                     Course Description  \
0     Write a Full Length Feature Film Script  In th...   
1     By the end of this guided project, you will be...   
2     This course consists of a general presentation...   
3     When it comes to numbers, there is always more...   
4     In this course you�ll learn how to effectively...   
...                                                 ...   
3517  In the capstone, students will build a series ...   
3518  �Give me liberty, or give me death:� Rememberi...   
3519  �Megatrends� heavily influence today�s organis...   
3520  This course teaches dynamics, one of the basic...   
3521  In this course, "Architecting with Google Kube...   

                                                 Skills  
0     Drama  Comedy  peering  screenwriting  film  D...  
1     Finance  business plan  persona (user experien...  
2     chemistry  physics  Solar Energy  film  lambda...  
3     accounts receivable  dupont analysis  analysis...  
4     Data Analysis  select (sql)  database manageme...  
...                                                 ...  
3517  Databases  syntax  analysis  web  Data Visuali...  
3518  retirement  Causality  career  history of the ...  
3519  analytics  tableau software  Business Intellig...  
3520  Angular  Mechanical Design  fluid mechanics  F...  
3521  bigtable  bigquery  SQL  Google Cloud Platform...  

[3522 rows x 7 columns]

In [5]:
df.shape

(3522, 7)

In [6]:
df.shape[0]

3522

In [7]:
df["Course Name"][0]

'Write A Feature Length Screenplay For Film Or Television'

In [8]:
ans=[]
for i in range(df.shape[0]):
    val=[]
    val.append(df["Course Name"][i])
    val.append(df["Course Description"][i])
    val.append(df["Skills"][i])
    ans.append(" ".join(val))
ans    

['Write A Feature Length Screenplay For Film Or Television Write a Full Length Feature Film Script  In this course, you will write a complete, feature-length screenplay for film or television, be it a serious drama or romantic comedy or anything in between. You�ll learn to break down the creative process into components, and you�ll discover a structured process that allows you to produce a polished and pitch-ready script by the end of the course. Completing this project will increase your confidence in your ideas and abilities, and you�ll feel prepared to pitch your first script and get started on your next. This is a course designed to tap into your creativity and is based in "Active Learning". Most of the actual learning takes place within your own activities - that is, writing! You will learn by doing.  Here is a link to a TRAILER for the course. To view the trailer, please copy and paste the link into your browser. https://vimeo.com/382067900/b78b800dc0  Learner review: "Love the a

In [9]:
df["Data"]=ans
df

Course Name  \
0     Write A Feature Length Screenplay For Film Or ...   
1     Business Strategy: Business Model Canvas Analy...   
2                         Silicon Thin Film Solar Cells   
3                                  Finance for Managers   
4          Retrieve Data using Single-Table SQL Queries   
...                                                 ...   
3517  Capstone: Retrieving, Processing, and Visualiz...   
3518                   Patrick Henry: Forgotten Founder   
3519  Business intelligence and data analytics: Gene...   
3520                                Rigid Body Dynamics   
3521  Architecting with Google Kubernetes Engine: Pr...   

                                             University Difficulty Level  \
0                             Michigan State University         Beginner   
1                              Coursera Project Network         Beginner   
2                                   �cole Polytechnique         Advanced   
3                                  IESE Business School     Intermediate   
4                              Coursera Project Network         Beginner   
...                                                 ...              ...   
3517                             University of Michigan         Beginner   
3518                             University of Virginia     Intermediate   
3519                               Macquarie University         Advanced   
3520  Korea Advanced Institute of Science and Techno...         Beginner   
3521                                       Google Cloud     Intermediate   

     Course Rating                                         Course URL  \
0              4.8  https://www.coursera.org/learn/write-a-feature...   
1              4.8  https://www.coursera.org/learn/canvas-analysis...   
2              4.1  https://www.coursera.org/learn/silicon-thin-fi...   
3              4.8  https://www.coursera.org/learn/operational-fin...   
4              4.6  https://www.coursera.org/learn/single-table-sq...   
...            ...                                                ...   
3517           4.6  https://www.coursera.org/learn/python-data-vis...   
3518           4.9               https://www.coursera.org/learn/henry   
3519           4.6  https://www.coursera.org/learn/business-intell...   
3520           4.6  https://www.coursera.org/learn/rigid-body-dyna...   
3521           4.7  https://www.coursera.org/learn/deploying-secur...   

                                     Course Description  \
0     Write a Full Length Feature Film Script  In th...   
1     By the end of this guided project, you will be...   
2     This course consists of a general presentation...   
3     When it comes to numbers, there is always more...   
4     In this course you�ll learn how to effectively...   
...                                                 ...   
3517  In the capstone, students will build a series ...   
3518  �Give me liberty, or give me death:� Rememberi...   
3519  �Megatrends� heavily influence today�s organis...   
3520  This course teaches dynamics, one of the basic...   
3521  In this course, "Architecting with Google Kube...   

                                                 Skills  \
0     Drama  Comedy  peering  screenwriting  film  D...   
1     Finance  business plan  persona (user experien...   
2     chemistry  physics  Solar Energy  film  lambda...   
3     accounts receivable  dupont analysis  analysis...   
4     Data Analysis  select (sql)  database manageme...   
...                                                 ...   
3517  Databases  syntax  analysis  web  Data Visuali...   
3518  retirement  Causality  career  history of the ...   
3519  analytics  tableau software  Business Intellig...   
3520  Angular  Mechanical Design  fluid mechanics  F...   
3521  bigtable  bigquery  SQL  Google Cloud Platform...   

                                                   Data  
0     Write A Feature Length Screenplay For Film Or ...  
1     Busin

In [10]:
nlp=spacy.load("en_core_web_sm")

def preprocess(text):
    doc=nlp(text)
    filtered_token=[]
    for token in doc:
        if token.is_stop or token.is_punct:
            continue
        filtered_token.append(token.lemma_)
    return " ".join(filtered_token)

print(preprocess(df["Data"][0]))
    

write Feature Length Screenplay Film Television write Length Feature Film Script   course write complete feature length screenplay film television drama romantic comedy � ll learn break creative process component � ll discover structured process allow produce polished pitch ready script end course complete project increase confidence idea ability � ll feel prepared pitch script start course design tap creativity base Active Learning actual learning take place activity write learn   link trailer course view trailer copy paste link browser https://vimeo.com/382067900/b78b800dc0   Learner review love approach Professor Wheeler take course point easy follow informative definitely recommend interested take Screenplay writing course   course curriculum simple adopt professional writer room process � ll write post work peer review share feedback peer revise work feedback receive peer real world feel professional writer room prior experience writer require proponent Experiential Learning Activ

In [11]:
def doeverything(val):
    df1=df[val]
    df1=df1.apply(lambda x: str(x))
    prep=[]
    for i in range(len(df1)):
        prep.append(preprocess(df1[i]))
    return prep

In [12]:
preprocessed=doeverything("Data")

In [13]:
preprocessed

['write Feature Length Screenplay Film Television write Length Feature Film Script   course write complete feature length screenplay film television drama romantic comedy � ll learn break creative process component � ll discover structured process allow produce polished pitch ready script end course complete project increase confidence idea ability � ll feel prepared pitch script start course design tap creativity base Active Learning actual learning take place activity write learn   link trailer course view trailer copy paste link browser https://vimeo.com/382067900/b78b800dc0   Learner review love approach Professor Wheeler take course point easy follow informative definitely recommend interested take Screenplay writing course   course curriculum simple adopt professional writer room process � ll write post work peer review share feedback peer revise work feedback receive peer real world feel professional writer room prior experience writer require proponent Experiential Learning Act

In [14]:
df["Preprocessed"]=preprocessed

In [15]:
df

Course Name  \
0     Write A Feature Length Screenplay For Film Or ...   
1     Business Strategy: Business Model Canvas Analy...   
2                         Silicon Thin Film Solar Cells   
3                                  Finance for Managers   
4          Retrieve Data using Single-Table SQL Queries   
...                                                 ...   
3517  Capstone: Retrieving, Processing, and Visualiz...   
3518                   Patrick Henry: Forgotten Founder   
3519  Business intelligence and data analytics: Gene...   
3520                                Rigid Body Dynamics   
3521  Architecting with Google Kubernetes Engine: Pr...   

                                             University Difficulty Level  \
0                             Michigan State University         Beginner   
1                              Coursera Project Network         Beginner   
2                                   �cole Polytechnique         Advanced   
3                                  IESE Business School     Intermediate   
4                              Coursera Project Network         Beginner   
...                                                 ...              ...   
3517                             University of Michigan         Beginner   
3518                             University of Virginia     Intermediate   
3519                               Macquarie University         Advanced   
3520  Korea Advanced Institute of Science and Techno...         Beginner   
3521                                       Google Cloud     Intermediate   

     Course Rating                                         Course URL  \
0              4.8  https://www.coursera.org/learn/write-a-feature...   
1              4.8  https://www.coursera.org/learn/canvas-analysis...   
2              4.1  https://www.coursera.org/learn/silicon-thin-fi...   
3              4.8  https://www.coursera.org/learn/operational-fin...   
4              4.6  https://www.coursera.org/learn/single-table-sq...   
...            ...                                                ...   
3517           4.6  https://www.coursera.org/learn/python-data-vis...   
3518           4.9               https://www.coursera.org/learn/henry   
3519           4.6  https://www.coursera.org/learn/business-intell...   
3520           4.6  https://www.coursera.org/learn/rigid-body-dyna...   
3521           4.7  https://www.coursera.org/learn/deploying-secur...   

                                     Course Description  \
0     Write a Full Length Feature Film Script  In th...   
1     By the end of this guided project, you will be...   
2     This course consists of a general presentation...   
3     When it comes to numbers, there is always more...   
4     In this course you�ll learn how to effectively...   
...                                                 ...   
3517  In the capstone, students will build a series ...   
3518  �Give me liberty, or give me death:� Rememberi...   
3519  �Megatrends� heavily influence today�s organis...   
3520  This course teaches dynamics, one of the basic...   
3521  In this course, "Architecting with Google Kube...   

                                                 Skills  \
0     Drama  Comedy  peering  screenwriting  film  D...   
1     Finance  business plan  persona (user experien...   
2     chemistry  physics  Solar Energy  film  lambda...   
3     accounts receivable  dupont analysis  analysis...   
4     Data Analysis  select (sql)  database manageme...   
...                                                 ...   
3517  Databases  syntax  analysis  web  Data Visuali...   
3518  retirement  Causality  career  history of the ...   
3519  analytics  tableau software  Business Intellig...   
3520  Angular  Mechanical Design  fluid mechanics  F...   
3521  bigtable  bigquery  SQL  Google Cloud Platform...   

                                                   Data  \
0     Write A Feature Length Screenplay For Film Or ...   
1     Bus

In [16]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

In [17]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [18]:
bert_preprocess = hub.KerasLayer("bert_en_uncased_preprocess_3")

In [19]:
bert_encoder=hub.KerasLayer("bert_en_uncased_L-12_H-768_A-12_4")

In [20]:
def get_sentence_embeding(sentences):
    preprocessed_text = bert_preprocess(sentences)
    return bert_encoder(preprocessed_text)['pooled_output']

In [21]:
#test
text_test = ['nice movie indeed','I love python programming']
text_preprocessed = bert_preprocess(text_test)
text_preprocessed.keys()

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [22]:
text_preprocessed['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

In [23]:
text_preprocessed['input_type_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

In [24]:
text_preprocessed['input_word_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [25]:
bert_results = bert_encoder(text_preprocessed)

In [26]:
bert_results

{'pooled_output': <tf.Tensor: shape=(2, 768), dtype=float32, numpy=
 array([[-0.7917741 , -0.21411933,  0.49769458, ...,  0.2446516 ,
         -0.47334474,  0.8175871 ],
        [-0.9171232 , -0.47935176, -0.78656995, ..., -0.6175179 ,
         -0.7102687 ,  0.921843  ]], dtype=float32)>,
 'encoder_outputs': [<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
  array([[[ 0.12901424,  0.00644747, -0.03614966, ...,  0.04999633,
            0.06149189, -0.02657543],
          [ 1.1753384 ,  1.2140785 ,  1.1569982 , ...,  0.11634388,
           -0.3585534 , -0.4049018 ],
          [ 0.03859033,  0.53869975, -0.21089774, ...,  0.21858197,
            0.7260166 , -1.1158603 ],
          ...,
          [-0.07587022, -0.25421908,  0.7075512 , ...,  0.50541985,
           -0.18878683,  0.1502833 ],
          [-0.16066611, -0.28089672,  0.57597065, ...,  0.5275855 ,
           -0.11141385,  0.02887556],
          [-0.04428175, -0.2027959 ,  0.5909356 , ...,  0.8133835 ,
           -0.3907580

In [27]:
bert_results.keys()

dict_keys(['pooled_output', 'encoder_outputs', 'sequence_output', 'default'])

In [28]:
#real thing

In [29]:
get_sentence_embeding([
    "Give me a Python Data Science Program", 
    "Give me a course on Distributed Systems"]
)

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.8435169 , -0.5132727 , -0.8884573 , ..., -0.7474888 ,
        -0.7531474 ,  0.91964483],
       [-0.8720835 , -0.50543964, -0.9444669 , ..., -0.85847497,
        -0.7174535 ,  0.8808299 ]], dtype=float32)>

In [30]:
val=get_sentence_embeding(df["Preprocessed"])

In [31]:
val

<tf.Tensor: shape=(3522, 768), dtype=float32, numpy=
array([[-0.74622476, -0.6500915 , -0.97331035, ..., -0.9347204 ,
        -0.6507058 ,  0.557929  ],
       [-0.79688156, -0.38299668, -0.77418655, ..., -0.73146003,
        -0.526878  ,  0.5573205 ],
       [-0.75623655, -0.43807015, -0.8168113 , ..., -0.8457639 ,
        -0.58033746,  0.5258382 ],
       ...,
       [-0.7735495 , -0.49222055, -0.83664984, ..., -0.7512628 ,
        -0.61253035,  0.64297664],
       [-0.78648424, -0.6763036 , -0.9313461 , ..., -0.8407315 ,
        -0.6778654 ,  0.6504392 ],
       [-0.81245095, -0.5703852 , -0.8583164 , ..., -0.76013225,
        -0.71162575,  0.76523614]], dtype=float32)>

In [32]:
val[0]

<tf.Tensor: shape=(768,), dtype=float32, numpy=
array([-7.4622476e-01, -6.5009153e-01, -9.7331035e-01,  6.8556696e-01,
        7.6483101e-01, -2.4956359e-01,  4.1966099e-01,  4.7476378e-01,
       -8.7794662e-01, -9.9996841e-01, -4.2222464e-01,  9.4220090e-01,
        9.4514793e-01,  7.0011008e-01,  7.1804833e-01, -5.8612722e-01,
        6.9648184e-02, -6.3730222e-01,  3.3333945e-01,  5.9624970e-01,
        6.8775570e-01,  9.9999899e-01, -2.2546779e-01,  4.3019438e-01,
        5.2998322e-01,  9.9129885e-01, -6.9393873e-01,  7.2157240e-01,
        8.1546640e-01,  6.7802984e-01, -3.3509851e-01,  4.7899339e-01,
       -9.6577787e-01, -3.6950293e-01, -9.8496222e-01, -9.7988915e-01,
        4.9066490e-01, -2.7122825e-01, -6.0041834e-02, -8.8168375e-02,
       -6.3331121e-01,  4.3820810e-01,  9.9998355e-01, -4.8485720e-01,
        4.8991463e-01, -3.2765883e-01, -1.0000000e+00,  3.0224714e-01,
       -6.8467993e-01,  9.4482672e-01,  9.0965933e-01,  9.4703227e-01,
        3.1155270e-01,  5.030

In [38]:
user_inp="I am a beginner looking for a Python programming course that covers essential programming elements, basic Python programs, expressions, variables, functions, logic, conditionals, Python modules, and practical tasks. I want to learn how to think like a computer programmer and write Python programs. The course should use Python 3 and preferably provide a beginner-friendly development environment like CodeSkulptor that runs in a web browser. I'm also interested in progressing to more advanced desktop development environments in later courses."

In [39]:
def check(user_inp):
    user_inp=preprocess(user_inp)
    sent_embd=get_sentence_embeding([user_inp])
    return sent_embd


In [35]:
from sklearn.metrics.pairwise import cosine_similarity

In [41]:
sent_embd=check(user_inp)
simm=[]
for i in range(len(val)):
    simm.append(cosine_similarity([val[i]],sent_embd))
#print(simm[:10])
final=simm[:]
final.sort(reverse=True)
ans=[]
for i in range(40):
    check_val=final[i]
    #print(check_val)
    for j in range(len(val)):
        if(simm[j]==check_val):
            #print(simm[j])
            ans.append(df["Course Name"][j])

print(ans)
    

['Code Yourself! An Introduction to Programming', 'Fundamentals of Network Communication', 'Linux Tools for Developers', 'Software Design as an Abstraction', 'Learn to Program: The Fundamentals', 'Adjectives and Adjective Clauses', 'Digital Systems: From Logic Gates to Processors', 'Programming with Scratch', 'Create Your First Application with Java Using Networking', 'Capstone:  Autonomous Runway Detection for IoT', 'Concurrency in Go', 'Learn Java and JavaFX by creating a Graphical Calculator', 'Introduction to TCP/IP', 'Easing the Transition to GIMP for Photoshop Users', 'Python Data Structures', 'Transfer Learning for Food Classification', 'Customer Journey Prototyping in XD', 'Concept Art for Video Games', 'Big data and Language 1', 'Building a Toolkit for Your Sales Process', 'Principles of Photo Composition and Digital Image Post-Production', 'Software Design Threats and Mitigations', 'Noun Clauses and Conditionals', 'Python Data Visualization', 'Introduction to PicsArt for Soci

In [42]:
userinp_1="I am a beginner looking for an IoT course that covers the importance of IoT in society, components of typical IoT devices, trends in IoT, IoT design considerations and constraints, interfacing with the physical world, design trade-offs between hardware and software, networking for IoT, and the role of Python in IoT development. The course should cover the definition of the Internet of Things, embedded systems and their components, hardware and software interactions in IoT devices, operating systems for IoT, networking protocols, and the structure of the Internet. I'm particularly interested in learning how Python is used in IoT applications. Can you recommend a suitable course?"

In [43]:
sent_embd=check(userinp_1)
simm=[]
for i in range(len(val)):
    simm.append(cosine_similarity([val[i]],sent_embd))
#print(simm[:10])
final=simm[:]
final.sort(reverse=True)
ans=[]
for i in range(40):
    check_val=final[i]
    #print(check_val)
    for j in range(len(val)):
        if(simm[j]==check_val):
            #print(simm[j])
            ans.append(df["Course Name"][j])

print(ans)
    

['Packet Switching Networks and Algorithms', 'Human-Centered Design: an Introduction', 'Application Systems Programming', 'Tweet Emotion Recognition with TensorFlow', 'Religions and Society in China', 'Engineering Maintainable Android Apps', 'Clinical Natural Language Processing', '3D Interaction Design in Virtual Reality', 'Increase Student Buy in with Google Slides', 'Models & Frameworks to Support Sales Planning', 'K-12 Blended & Online Learning', 'Vector Calculus for Engineers', 'Evaluating Designs with Users', 'MRI Fundamentals', 'Introduction to Blockchain Technologies', 'Calculus and Optimization for Machine Learning', 'An Introduction to Accessibility and Inclusive Design', 'Algorithms, Part II', 'An Intuitive Introduction to Probability', 'Homeland Security and Cybersecurity Future', 'Apply Generative Adversarial Networks (GANs)', 'Introduction to Programming and Animation with Alice', 'Clinical Terminology for International and U.S. Students', 'FIFA20 Data Exploration using P